#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Deploy GSMRouter + sGHORouter to local Anvil fork and update .env.local
# ============================================================================
# Prerequisites:
#   - Anvil running:  anvil --fork-url https://eth.llamarpc.com --chain-id 31337
#   - Foundry installed (forge, cast)
#
# Usage:
#   cd frontend-app && ./scripts/deploy-local.sh
# ============================================================================

RPC="${ANVIL_RPC_URL:-http://127.0.0.1:8545}"
CONTRACTS_DIR="$(cd "$(dirname "$0")/../../contracts" && pwd)"
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.local"

# Anvil default private key #0
PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# Mainnet sGHO (StataTokenV2 GHO vault deployed by Aave)
# If you have a custom sGHO, set SGHO env var before running.
# For testing, we use the mainnet StataTokenV2 for GHO which is ERC4626-compatible.
SGHO="${SGHO:-0x73edDFa87C71ADdC275c2b9890f5c3a8480bC9E6}"

GREEN='\033[0;32m'
NC='\033[0m'
ok() { echo -e "  ${GREEN}[OK]${NC} $1"; }

echo ""
echo "======================================"
echo "  Deploy to Local Anvil Fork"
echo "======================================"
echo ""
echo "  RPC:       $RPC"
echo "  Contracts: $CONTRACTS_DIR"
echo "  Env file:  $ENV_FILE"
echo ""

# ---- 1. Deploy GSMRouter ----
echo "Deploying GSMRouter..."
GSM_ROUTER_OUTPUT=$(cd "$CONTRACTS_DIR" && \
  PRIVATE_KEY="$PRIVATE_KEY" \
  forge script script/DeployGSMRouter.s.sol \
    --rpc-url "$RPC" \
    --broadcast \
    --silent 2>&1)

GSM_ROUTER_ADDR=$(echo "$GSM_ROUTER_OUTPUT" | grep -oE '0x[0-9a-fA-F]{40}' | tail -1)
if [ -z "$GSM_ROUTER_ADDR" ]; then
  echo "  Failed to deploy GSMRouter. Output:"
  echo "$GSM_ROUTER_OUTPUT"
  exit 1
fi
ok "GSMRouter deployed at $GSM_ROUTER_ADDR"

# ---- 2. Deploy sGHORouter ----
echo "Deploying sGHORouter..."
SGHO_ROUTER_OUTPUT=$(cd "$CONTRACTS_DIR" && \
  PRIVATE_KEY="$PRIVATE_KEY" \
  GSM_ROUTER="$GSM_ROUTER_ADDR" \
  SGHO="$SGHO" \
  forge script script/DeploySGHORouter.s.sol \
    --rpc-url "$RPC" \
    --broadcast \
    --silent 2>&1)

SGHO_ROUTER_ADDR=$(echo "$SGHO_ROUTER_OUTPUT" | grep -oE '0x[0-9a-fA-F]{40}' | tail -1)
if [ -z "$SGHO_ROUTER_ADDR" ]; then
  echo "  Failed to deploy sGHORouter. Output:"
  echo "$SGHO_ROUTER_OUTPUT"
  exit 1
fi
ok "sGHORouter deployed at $SGHO_ROUTER_ADDR"

# ---- 3. Write .env.local ----
echo "Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy-local.sh -- $(date)
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=placeholder_replace_me

NEXT_PUBLIC_SGHO_ROUTER_ADDRESS=$SGHO_ROUTER_ADDR
NEXT_PUBLIC_GSM_ROUTER_ADDRESS=$GSM_ROUTER_ADDR
NEXT_PUBLIC_SGHO_ADDRESS=$SGHO
NEXT_PUBLIC_GHO_ADDRESS=0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f
NEXT_PUBLIC_USDC_ADDRESS=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
NEXT_PUBLIC_USDT_ADDRESS=0xdAC17F958D2ee523a2206206994597C13D831ec7
NEXT_PUBLIC_GSM_USDC_ADDRESS=0xFeeb6FE430B7523fEF2a38327241eE7153779535
NEXT_PUBLIC_GSM_USDT_ADDRESS=0x535b2f7C20B9C83d70e519cf9991578eF9816B7B

NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_ANVIL_RPC_URL=http://127.0.0.1:8545
EOF
ok "Updated .env.local"

echo ""
echo "======================================"
echo "  Deployment Summary"
echo "======================================"
echo "  GSMRouter:   $GSM_ROUTER_ADDR"
echo "  sGHORouter:  $SGHO_ROUTER_ADDR"
echo "  sGHO Vault:  $SGHO"
echo ""
echo "Next steps:"
echo "  1. npm run faucet -- <YOUR_ADDRESS>"
echo "  2. npm run dev"
echo "  3. Open http://localhost:3000"
echo ""
